// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcaojogjfwbjfqalvese.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYW9qb2dqZndiamZxYWx2ZXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NzQ3MjUsImV4cCI6MjA3ODE1MDcyNX0.3wQUyh6jDGI1mTxE400OVova6-qml74Cco23_0L9CEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});